### Tarea 09 - Eliminación Gaussiana vs Gauss Jordan 

Nombre: Carolay Pillajo

Curso: GR1CC

1. Para cada uno de los siguientes sistemas lineales, obtenga, de ser posible, una solución con métodos gráficos. Explique los resultados desde un punto de vista geométrico.

a) 

$𝑥_1 + 2𝑥_2 = 0,$

$x_1 − 𝑥_2 = 0.$


In [8]:
import numpy as np

A = np.array([
    [1, 2, 0],
    [1, -1, 0]
], dtype=float)

print("Matriz inicial:")
print(A)

print("\nResolución:")
factor = A[1, 0] / A[0, 0]
print(f"\nR2 = R2 - ({factor}) * R1 \n")

A[1] = A[1] - factor * A[0]

print(A)

x2 = A[1, 2] / A[1, 1]
x1 = (A[0, 2] - A[0, 1] * x2) / A[0, 0]

print("\nSoluciones:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")

Matriz inicial:
[[ 1.  2.  0.]
 [ 1. -1.  0.]]

Resolución:

R2 = R2 - (1.0) * R1 

[[ 1.  2.  0.]
 [ 0. -3.  0.]]

Soluciones:
x1 = 0.0
x2 = -0.0


b)

$x_1 + 2𝑥_2 = 3,$

$−2𝑥_1 − 4𝑥_2 = 6.$

In [22]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [-2, -4, 6]
], dtype=float)

print("Matriz inicial:")
print(A)

print("\nResolución:")

factor = A[1, 0] / A[0, 0]
print(f"\nR2 = R2 - ({factor}) * R1\n")

A[1] = A[1] - factor * A[0]

print(A)

if A[1,0] == 0 and A[1,1] == 0 and A[1,2] != 0:
    print("\nResultado:")
    print("0 = ", A[1,2])
    print("El sistema es inconsistente -> NO tiene solución.")
else:
    x2 = A[1, 2] / A[1, 1]
    x1 = (A[0, 2] - A[0, 1] * x2) / A[0, 0]

    print("\nSoluciones:")
    print(f"x1 = {x1}")
    print(f"x2 = {x2}")

Matriz inicial:
[[ 1.  2.  3.]
 [-2. -4.  6.]]

Resolución:

R2 = R2 - (-2.0) * R1

[[ 1.  2.  3.]
 [ 0.  0. 12.]]

Resultado:
0 =  12.0
El sistema es inconsistente -> NO tiene solución.


c)

$2𝑥_1 + 𝑥_2 = −1,$

$𝑥_1 + 𝑥_2 = 2,$

$x_1 − 3𝑥_2 = 5.$

In [ ]:
import numpy as np

A = np.array([
    [2, 1, -1],
    [1, 1,  2],
    [1, -3, 5]
], dtype=float)

print("Matriz inicial:")
print(A)

print("\nResolución:")
factor21 = A[1, 0] / A[0, 0]
factor31 = A[2, 0] / A[0, 0]

print(f"\nR2 = R2 - ({factor21}) * R1")
print(f"R3 = R3 - ({factor31}) * R1\n")

A[1] = A[1] - factor21 * A[0]
A[2] = A[2] - factor31 * A[0]

print(A)

factor32 = A[2, 1] / A[1, 1]
print(f"\nR3 = R3 - ({factor32}) * R2\n")

A[2] = A[2] - factor32 * A[1]

print(A)

print("\nResultado:")
print("\n0 = ", A[2,2])
print("El sistema es inconsistente -> No tiene solución")

Matriz inicial:
[[ 2.  1. -1.]
 [ 1.  1.  2.]
 [ 1. -3.  5.]]

Resolución:

R2 = R2 - (0.5) * R1
R3 = R3 - (0.5) * R1

[[ 2.   1.  -1. ]
 [ 0.   0.5  2.5]
 [ 0.  -3.5  5.5]]

R3 = R3 - (-7.0) * R2

[[ 2.   1.  -1. ]
 [ 0.   0.5  2.5]
 [ 0.   0.  23. ]]

Resultado:

0 =  23.0
El sistema es inconsistente -> No tiene solución


d)

$2𝑥_1 + 𝑥_2 + 𝑥_3 = 1,$

$2𝑥_1 + 4𝑥_2 − 𝑥_3 = −1.$

In [3]:
import numpy as np

A = np.array([
    [2, 1, 1, 1],
    [2, 4, -1, -1]
], dtype=float)

print("Matriz inicial:")
print(A)

print("\nResolución:")

factor = A[1, 0] / A[0, 0]
print(f"\nR2 = R2 - ({factor}) * R1\n")

A[1] = A[1] - factor * A[0]

print(A)

coef = A[:, :3]
aug = A

rango_coef = np.linalg.matrix_rank(coef)
rango_aug = np.linalg.matrix_rank(aug)
num_incog = 3

if rango_coef < num_incog and rango_coef == rango_aug:
    print("\nEl sistema tiene infinitas soluciones.")
else:
    print("\nEl sistema tiene una única solución o es incompatible.")

Matriz inicial:
[[ 2.  1.  1.  1.]
 [ 2.  4. -1. -1.]]

Resolución:

R2 = R2 - (1.0) * R1

[[ 2.  1.  1.  1.]
 [ 0.  3. -2. -2.]]

El sistema tiene infinitas soluciones.


2. Utilice la eliminación gaussiana con sustitución hacia atrás y aritmética de redondeo de dos dígitos para resolver los siguientes sistemas lineales. No reordene las ecuaciones. (La solución exacta para cada sistema es $𝑥_1 = −1, x_2 = 2, 𝑥_3 = 3$.)

a)

$-x_1 + 4x_2 + x_3 = 8,$

$5/3x_1 + 2/3x_2 + 2/3x_3 = 1,$

$x_1 + x_2 + 4x_3 = 11.$

In [25]:
def r(x):
    return round(x, 2)

A = [
    [-1.0, 4.0, 1.0, 8.0],
    [5/3, 2/3, 2/3, 1.0],
    [1.0, 1.0, 4.0, 11.0]
]

print("Matriz inicial:")
for fila in A:
    print(fila)

print("\nResolución\n")

m21 = r(A[1][0] / A[0][0])
print(f"m21 = {m21}")
A[1] = [r(A[1][j] - r(m21 * A[0][j])) for j in range(4)]

m31 = r(A[2][0] / A[0][0])
print(f"m31 = {m31}")
A[2] = [r(A[2][j] - r(m31 * A[0][j])) for j in range(4)]

print(" ")
for fila in A:
    print(fila)

print(" ")

m32 = r(A[2][1] / A[1][1])
print(f"m32 = {m32}")
A[2] = [r(A[2][j] - r(m32 * A[1][j])) for j in range(4)]

print(" ")
for fila in A:
    print(fila)

print("\nSustitución hacia atrás")

x3 = r(A[2][3] / A[2][2])
print(f"x3 = {x3}")

x2 = r((A[1][3] - r(A[1][2] * x3)) / A[1][1])
print(f"x2 = {x2}")

x1 = r((A[0][3] - r(A[0][1] * x2) - r(A[0][2] * x3)) / A[0][0])
print(f"x1 = {x1}")

print("\nSolución con redondeo")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")

Matriz inicial:
[-1.0, 4.0, 1.0, 8.0]
[1.6666666666666667, 0.6666666666666666, 0.6666666666666666, 1.0]
[1.0, 1.0, 4.0, 11.0]

Resolución

m21 = -1.67
m31 = -1.0
 
[-1.0, 4.0, 1.0, 8.0]
[-0.0, 7.35, 2.34, 14.36]
[0.0, 5.0, 5.0, 19.0]
 
m32 = 0.68
 
[-1.0, 4.0, 1.0, 8.0]
[-0.0, 7.35, 2.34, 14.36]
[0.0, 0.0, 3.41, 9.24]

Sustitución hacia atrás
x3 = 2.71
x2 = 1.09
x1 = -0.93

Solución con redondeo
x1 = -0.93
x2 = 1.09
x3 = 2.71


b) 

$4x_1 + 2x_2 - x_3 = -5,$

$1/9 x_1 + 1/9 x_2 - 1/3 x_3 = 1,$

$x_1 + 4x_2 + 2x_3 = 9.$


In [33]:
def r(x):
    return round(x, 2)

A = [
    [4.0, 2.0, -1.0, -5.0],
    [1/9, 1/9, -1/3, -1.0],
    [1.0, 4.0, 2.0, 9.0]
]

print("Matriz inicial:")
for fila in A:
    print(fila)
    
print("\nResolución\n")

m21 = r(A[1][0] / A[0][0])
print(f"m21 = {m21}")
A[1] = [r(A[1][j] - r(m21 * A[0][j])) for j in range(4)]

m31 = r(A[2][0] / A[0][0])
print(f"m31 = {m31}")
A[2] = [r(A[2][j] - r(m31 * A[0][j])) for j in range(4)]

print(" ")
for fila in A:
    
    print(fila)

print(" ")
m32 = r(A[2][1] / A[1][1])
print(f"m32 = {m32}")
A[2] = [r(A[2][j] - r(m32 * A[1][j])) for j in range(4)]

print(" ")
for fila in A:
    print(fila)

print("\nSustitución hacia atrás")

x3 = r(A[2][3] / A[2][2])
print(f"x3 = {x3}")

x2 = r((A[1][3] - r(A[1][2] * x3)) / A[1][1])
print(f"x2 = {x2}")

x1 = r((A[0][3] - r(A[0][1] * x2) - r(A[0][2] * x3)) / A[0][0])
print(f"x1 = {x1}")

print("\nSolución con redondeo")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")

Matriz inicial:
[4.0, 2.0, -1.0, -5.0]
[0.1111111111111111, 0.1111111111111111, -0.3333333333333333, -1.0]
[1.0, 4.0, 2.0, 9.0]

Resolución

m21 = 0.03
m31 = 0.25
 
[4.0, 2.0, -1.0, -5.0]
[-0.01, 0.05, -0.3, -0.85]
[0.0, 3.5, 2.25, 10.25]
 
m32 = 70.0
 
[4.0, 2.0, -1.0, -5.0]
[-0.01, 0.05, -0.3, -0.85]
[0.7, 0.0, 23.25, 69.75]

Sustitución hacia atrás
x3 = 3.0
x2 = 1.0
x1 = -1.0

Solución con redondeo
x1 = -1.0
x2 = 1.0
x3 = 3.0


3. Utilice el algoritmo de eliminación gaussiana para resolver, de ser posible, los siguientes sistemas lineales, y determine si se necesitan intercambios de fila:

a)

$x_1 - x_2 + 3x_3 =2,$

$3x_1 - 3x_2 + x_3 =-1,$

$x_1 + x_2 =3.$

In [34]:
def p(A):
    for fila in A:
        print(fila)
    print()

A = [
    [1.0, -1.0, 3.0, 2.0],
    [3.0, -3.0, 1.0, -1.0],
    [1.0,  1.0, 0.0, 3.0]
]

print("Matriz inicial:")
p(A)

print("Resolución\n")

m21 = A[1][0] / A[0][0]
print(f"m21 = {m21}  -->  R2 = R2 - m21*R1")

A[1] = [
    A[1][j] - m21 * A[0][j] for j in range(4)
]

m31 = A[2][0] / A[0][0]
print(f"m31 = {m31}  -->  R3 = R3 - m31*R1")
print(" ")

A[2] = [
    A[2][j] - m31 * A[0][j] for j in range(4)
]

p(A)

A[1], A[2] = A[2], A[1]

p(A)

m32 = A[2][1] / A[1][1]
print(f"m32 = {m32}  -->  R3 = R3 - m32*R2")

A[2] = [
    A[2][j] - m32 * A[1][j] for j in range(4)
]

print("\nMatriz final:")
p(A)

print("Sustitución hacia atrás\n")

x3 = A[2][3] / A[2][2]
print(f"Ecuación 3: {A[2][2]}x3 = {A[2][3]}")
print(f"x3 = {x3}\n")

print(f"Ecuación 2:  {A[1][0]}x1 + {A[1][1]}x2 + {A[1][2]}x3 = {A[1][3]}")
x2 = (A[1][3] - A[1][2]*x3) / A[1][1]
print(f"Sustituyendo x3 = {x3}")
print(f"x2 = {x2}\n")

print(f"Ecuación 1:  {A[0][0]}x1 + {A[0][1]}x2 + {A[0][2]}x3 = {A[0][3]}")
x1 = (A[0][3] - A[0][1]*x2 - A[0][2]*x3) / A[0][0]
print(f"Sustituyendo x2 = {x2} y x3 = {x3}")
print(f"x1 = {x1}\n")

print("Solución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")

Matriz inicial:
[1.0, -1.0, 3.0, 2.0]
[3.0, -3.0, 1.0, -1.0]
[1.0, 1.0, 0.0, 3.0]

Resolución

m21 = 3.0  -->  R2 = R2 - m21*R1
m31 = 1.0  -->  R3 = R3 - m31*R1
 
[1.0, -1.0, 3.0, 2.0]
[0.0, 0.0, -8.0, -7.0]
[0.0, 2.0, -3.0, 1.0]

[1.0, -1.0, 3.0, 2.0]
[0.0, 2.0, -3.0, 1.0]
[0.0, 0.0, -8.0, -7.0]

m32 = 0.0  -->  R3 = R3 - m32*R2

Matriz final:
[1.0, -1.0, 3.0, 2.0]
[0.0, 2.0, -3.0, 1.0]
[0.0, 0.0, -8.0, -7.0]

Sustitución hacia atrás

Ecuación 3: -8.0x3 = -7.0
x3 = 0.875

Ecuación 2:  0.0x1 + 2.0x2 + -3.0x3 = 1.0
Sustituyendo x3 = 0.875
x2 = 1.8125

Ecuación 1:  1.0x1 + -1.0x2 + 3.0x3 = 2.0
Sustituyendo x2 = 1.8125 y x3 = 0.875
x1 = 1.1875

Solución final
x1 = 1.1875
x2 = 1.8125
x3 = 0.875


b)

$2x_1 - 1.5x_2 + 3x_3 =1,$

$-x_1 + 2x_2 =3,$

$4x_1 - 4.5x_2 + 5x_3 =1.$

In [38]:
def p(A):
    for fila in A:
        print(fila)
    print()

A = [
    [2.0, -1.5, 3.0, 1.0],
    [-1.0, 0.0, 2.0, 3.0],
    [4.0, -4.5, 5.0, 1.0]
]

print("Matriz inicial:")
p(A)

print("Resolución\n")

m21 = A[1][0] / A[0][0]
print(f"m21 = {m21}  -->  R2 = R2 - m21*R1")

A[1] = [
    A[1][j] - m21 * A[0][j] for j in range(4)
]

m31 = A[2][0] / A[0][0]
print(f"m31 = {m31}  -->  R3 = R3 - m31*R1")

print(" ")
A[2] = [
    A[2][j] - m31 * A[0][j] for j in range(4)
]

p(A)

m32 = A[2][1] / A[1][1]
print(f"m32 = {m32}  -->  R3 = R3 - m32*R2")

A[2] = [
    A[2][j] - m32 * A[1][j] for j in range(4)
]

print("\nMatriz final:")
p(A)

print("Sustitución hacia atrás\n")

print(f"Ecuación 3:  {A[2][2]}x3 = {A[2][3]}")
x3 = A[2][3] / A[2][2]
print(f"x3 = {x3}\n")

print(f"Ecuación 2:  {A[1][1]}x2 + {A[1][2]}x3 = {A[1][3]}")
x2 = (A[1][3] - A[1][2]*x3) / A[1][1]
print(f"Sustituyendo x3 = {x3}")
print(f"x2 = {x2}\n")

print(f"Ecuación 1:  {A[0][0]}x1 + {A[0][1]}x2 + {A[0][2]}x3 = {A[0][3]}")
x1 = (A[0][3] - A[0][1]*x2 - A[0][2]*x3) / A[0][0]
print(f"Sustituyendo x2 = {x2} y x3 = {x3}")
print(f"x1 = {x1}\n")

print("Solución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")

Matriz inicial:
[2.0, -1.5, 3.0, 1.0]
[-1.0, 0.0, 2.0, 3.0]
[4.0, -4.5, 5.0, 1.0]

Resolución

m21 = -0.5  -->  R2 = R2 - m21*R1
m31 = 2.0  -->  R3 = R3 - m31*R1
 
[2.0, -1.5, 3.0, 1.0]
[0.0, -0.75, 3.5, 3.5]
[0.0, -1.5, -1.0, -1.0]

m32 = 2.0  -->  R3 = R3 - m32*R2

Matriz final:
[2.0, -1.5, 3.0, 1.0]
[0.0, -0.75, 3.5, 3.5]
[0.0, 0.0, -8.0, -8.0]

Sustitución hacia atrás

Ecuación 3:  -8.0x3 = -8.0
x3 = 1.0

Ecuación 2:  -0.75x2 + 3.5x3 = 3.5
Sustituyendo x3 = 1.0
x2 = -0.0

Ecuación 1:  2.0x1 + -1.5x2 + 3.0x3 = 1.0
Sustituyendo x2 = -0.0 y x3 = 1.0
x1 = -1.0

Solución final
x1 = -1.0
x2 = -0.0
x3 = 1.0


c)

$2x_1 = 3,$

$x_1 + 1.5x_2 = 4.5,$

$-3x_2 + 0.5x_3 = -6.6,$

$2x_1 - 2x_2 + x_3 + x_4 = 0.8 .$

In [4]:
def p(A):
    for fila in A:
        print(fila)
    print()

A = [
    [2.0, 0.0, 0.0, 0.0, 3.0],
    [1.0, 1.5, 0.0, 0.0, 4.5],
    [0.0, -3.0, 0.5, 0.0, -6.6],
    [2.0, -2.0, 1.0, 1.0, 0.8]
]

print("Matriz inicial:")
p(A)

print("Resolución\n")

m21 = A[1][0] / A[0][0]
print(f"m21 = {m21}  -->  R2 = R2 - m21*R1")
A[1] = [A[1][j] - m21*A[0][j] for j in range(5)]

m41 = A[3][0] / A[0][0]
print(f"m41 = {m41}  -->  R4 = R4 - m41*R1")
A[3] = [A[3][j] - m41*A[0][j] for j in range(5)]

print(" ")
p(A)

m32 = A[2][1] / A[1][1]
print(f"m32 = {m32}  -->  R3 = R3 - m32*R2")
A[2] = [A[2][j] - m32*A[1][j] for j in range(5)]

m42 = A[3][1] / A[1][1]
print(f"m42 = {m42}  -->  R4 = R4 - m42*R2")
A[3] = [A[3][j] - m42*A[1][j] for j in range(5)]

p(A)

m43 = A[3][2] / A[2][2]
print(f"m43 = {m43}  -->  R4 = R4 - m43*R3")
A[3] = [A[3][j] - m43*A[2][j] for j in range(5)]

print("\nMatriz final:")
p(A)

print("Sustitución hacia atrás\n")

print(f"Ecuación 4:  {A[3][3]}x4 = {A[3][4]}")
x4 = A[3][4] / A[3][3]
print(f"x4 = {x4}\n")

print(f"Ecuación 3:  {A[2][2]}x3 + {A[2][3]}x4 = {A[2][4]}")
x3 = (A[2][4] - A[2][3]*x4) / A[2][2]
print(f"Sustituyendo x4 = {x4}")
print(f"x3 = {x3}\n")

print(f"Ecuación 2:  {A[1][1]}x2 + {A[1][2]}x3 = {A[1][4]}")
x2 = (A[1][4] - A[1][2]*x3) / A[1][1]
print(f"Sustituyendo x3 = {x3}")
print(f"x2 = {x2}\n")

print(f"Ecuación 1:  {A[0][0]}x1 = {A[0][4]}")
x1 = A[0][4] / A[0][0]
print(f"x1 = {x1}\n")

print("Solución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")
print(f"x4 = {x4}")

Matriz inicial:
[2.0, 0.0, 0.0, 0.0, 3.0]
[1.0, 1.5, 0.0, 0.0, 4.5]
[0.0, -3.0, 0.5, 0.0, -6.6]
[2.0, -2.0, 1.0, 1.0, 0.8]

Resolución

m21 = 0.5  -->  R2 = R2 - m21*R1
m41 = 1.0  -->  R4 = R4 - m41*R1
 
[2.0, 0.0, 0.0, 0.0, 3.0]
[0.0, 1.5, 0.0, 0.0, 3.0]
[0.0, -3.0, 0.5, 0.0, -6.6]
[0.0, -2.0, 1.0, 1.0, -2.2]

m32 = -2.0  -->  R3 = R3 - m32*R2
m42 = -1.3333333333333333  -->  R4 = R4 - m42*R2
[2.0, 0.0, 0.0, 0.0, 3.0]
[0.0, 1.5, 0.0, 0.0, 3.0]
[0.0, 0.0, 0.5, 0.0, -0.5999999999999996]
[0.0, 0.0, 1.0, 1.0, 1.7999999999999998]

m43 = 2.0  -->  R4 = R4 - m43*R3

Matriz final:
[2.0, 0.0, 0.0, 0.0, 3.0]
[0.0, 1.5, 0.0, 0.0, 3.0]
[0.0, 0.0, 0.5, 0.0, -0.5999999999999996]
[0.0, 0.0, 0.0, 1.0, 2.999999999999999]

Sustitución hacia atrás

Ecuación 4:  1.0x4 = 2.999999999999999
x4 = 2.999999999999999

Ecuación 3:  0.5x3 + 0.0x4 = -0.5999999999999996
Sustituyendo x4 = 2.999999999999999
x3 = -1.1999999999999993

Ecuación 2:  1.5x2 + 0.0x3 = 3.0
Sustituyendo x3 = -1.1999999999999993
x2 = 2.0

Ecuac

d)

$x_1 + x_2 + x_4 = 2,$

$2x_1 + x_2 - x_3 + x_4 = 1,$

$4x_1 - x_2 - 2x_3 + 2x_4 = 0,$

$3x_1 - x_2 - x_3 + 2x_4 = -3. $

In [19]:
import numpy as np

A = np.array([
    [1, 1, 0, 1, 2],
    [2, 1, -1, 1, 1],
    [4, -1, -2, 2, 0],
    [3, -1, -1, 2, -3]
], dtype=float)

print("Matriz inicial:")
print(A)

print("\nResolución\n")

m21 = A[1,0] / A[0,0]
m31 = A[2,0] / A[0,0]
m41 = A[3,0] / A[0,0]

print(f"m21 = {m21}")
print(f"m31 = {m31}")
print(f"m41 = {m41}")
print(" ")

A[1] = A[1] - m21*A[0]
A[2] = A[2] - m31*A[0]
A[3] = A[3] - m41*A[0]

print(A)

m32 = A[2,1] / A[1,1]
m42 = A[3,1] / A[1,1]

print(" ")
print(f"m32 = {m32}")
print(f"m42 = {m42}")
print(" ")

A[2] = A[2] - m32*A[1]
A[3] = A[3] - m42*A[1]

print(A)

m43 = A[3,2] / A[2,2]
print(" ")
print(f"m43 = {m43}")

A[3] = A[3] - m43*A[2]

print("\nMatriz final:")
print(A)

print("\nSustitución hacia atrás")

x4 = A[3,4] / A[3,3]
print(f"x4 = {x4}")

x3 = (A[2,4] - A[2,3]*x4) / A[2,2]
print(f"x3 = {x3}")

x2 = (A[1,4] - A[1,2]*x3 - A[1,3]*x4) / A[1,1]
print(f"x2 = {x2}")

x1 = (A[0,4] - A[0,1]*x2 - A[0,2]*x3 - A[0,3]*x4) / A[0,0]
print(f"x1 = {x1}")

print("\nSolución final:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")
print(f"x4 = {x4}")
print("\nEl sistema es incompatible. No tiene solución.")

Matriz inicial:
[[ 1.  1.  0.  1.  2.]
 [ 2.  1. -1.  1.  1.]
 [ 4. -1. -2.  2.  0.]
 [ 3. -1. -1.  2. -3.]]

Resolución

m21 = 2.0
m31 = 4.0
m41 = 3.0
 
[[ 1.  1.  0.  1.  2.]
 [ 0. -1. -1. -1. -3.]
 [ 0. -5. -2. -2. -8.]
 [ 0. -4. -1. -1. -9.]]
 
m32 = 5.0
m42 = 4.0
 
[[ 1.  1.  0.  1.  2.]
 [ 0. -1. -1. -1. -3.]
 [ 0.  0.  3.  3.  7.]
 [ 0.  0.  3.  3.  3.]]
 
m43 = 1.0

Matriz final:
[[ 1.  1.  0.  1.  2.]
 [ 0. -1. -1. -1. -3.]
 [ 0.  0.  3.  3.  7.]
 [ 0.  0.  0.  0. -4.]]

Sustitución hacia atrás
x4 = -inf
x3 = inf
x2 = nan
x1 = nan

Solución final:
x1 = nan
x2 = nan
x3 = inf
x4 = -inf

El sistema es incompatible. No tiene solución.


C:\Users\PC\AppData\Local\Temp\ipykernel_20264\1685051944.py:54: RuntimeWarning: divide by zero encountered in scalar divide
  x4 = A[3,4] / A[3,3]
C:\Users\PC\AppData\Local\Temp\ipykernel_20264\1685051944.py:60: RuntimeWarning: invalid value encountered in scalar subtract
  x2 = (A[1,4] - A[1,2]*x3 - A[1,3]*x4) / A[1,1]
C:\Users\PC\AppData\Local\Temp\ipykernel_20264\1685051944.py:63: RuntimeWarning: invalid value encountered in scalar multiply
  x1 = (A[0,4] - A[0,1]*x2 - A[0,2]*x3 - A[0,3]*x4) / A[0,0]


4. Use el algoritmo de eliminación gaussiana y la aritmética computacional de precisión de 32 bits para resolver los siguientes sistemas lineales.

a)

$1/4x_1 + 1/5x_2 + 1/6x_3 = 9,$

$1/3x_1 + 1/4x_2 + 1/5x_3 = 8,$

$1/2x_1 + x_2 + 2x_3 = 8.$

In [22]:
import numpy as np

A = np.array([
    [1/4, 1/5, 1/6, 9],
    [1/3, 1/4, 1/5, 8],
    [1/2, 1.0, 2.0, 8]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución\n")

m21 = np.float32(A[1,0] / A[0,0])
m31 = np.float32(A[2,0] / A[0,0])

print(f"m21 = {m21}")
print(f"m31 = {m31}\n")

A[1] = np.float32(A[1] - m21*A[0])
A[2] = np.float32(A[2] - m31*A[0])

print(A, "\n")

m32 = np.float32(A[2,1] / A[1,1])
print(f"m32 = {m32}\n")

A[2] = np.float32(A[2] - m32*A[1])

print("Matriz final:")
print(A)

print("\nSustitución hacia atrás\n")

x3 = np.float32(A[2,3] / A[2,2])
print(f"x3 = {x3}")

x2 = np.float32((A[1,3] - A[1,2]*x3) / A[1,1])
print(f"x2 = {x2}")

x1 = np.float32((A[0,3] - A[0,2]*x3 - A[0,1]*x2) / A[0,0])
print(f"x1 = {x1}")

print("\nSolución final:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")

Matriz inicial:
[[0.25       0.2        0.16666667 9.        ]
 [0.33333334 0.25       0.2        8.        ]
 [0.5        1.         2.         8.        ]]

Resolución

m21 = 1.3333333730697632
m31 = 2.0

[[  0.25         0.2          0.16666667   9.        ]
 [  0.          -0.01666668  -0.02222224  -4.        ]
 [  0.           0.6          1.6666666  -10.        ]] 

m32 = -35.99997329711914

Matriz final:
[[ 2.5000000e-01  2.0000000e-01  1.6666667e-01  9.0000000e+00]
 [ 0.0000000e+00 -1.6666681e-02 -2.2222236e-02 -4.0000000e+00]
 [ 0.0000000e+00 -5.9604645e-08  8.6666673e-01 -1.5399989e+02]]

Sustitución hacia atrás

x3 = -177.69216918945312
x2 = 476.9226379394531
x1 = -227.07666015625

Solución final:
x1 = -227.07666015625
x2 = 476.9226379394531
x3 = -177.69216918945312


b)

$3.333x_1 + 15920x_2 - 10.333x_3 = 15913,$

$2.222x_1 + 16.71x_2 + 9.612x_3 = 28.544,$

$1.5611x_1 + 5.1791x_2 + 1.6852x_3 = 8.4254.$

In [25]:
import numpy as np

A = np.array([
    [3.3333, 15920,  -10.3333, 15913],
    [2.2222, 16.71,    9.612,   28.544],
    [1.5611, 5.1791,   1.6852,  8.4254]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución\n")

m21 = A[1,0] / A[0,0]
m31 = A[2,0] / A[0,0]

print(f"m21 = {m21}")
print(f"m31 = {m31}\n")

A[1] = A[1] - m21*A[0]
A[2] = A[2] - m31*A[0]

print(A)

m32 = A[2,1] / A[1,1]

print(f"\n m32 = {m32}\n")

A[2] = A[2] - m32*A[1]

print("Matriz final:")
print(A)

print("\nSustitución hacia atrás\n")

x3 = A[2,3] / A[2,2]
print(f"x3 = {x3}")

x2 = (A[1,3] - A[1,2]*x3) / A[1,1]
print(f"x2 = {x2}")

x1 = (A[0,3] - A[0,1]*x2 - A[0,2]*x3) / A[0,0]
print(f"x1 = {x1}")

print("\nSolución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")

Matriz inicial:
[[ 3.33330e+00  1.59200e+04 -1.03333e+01  1.59130e+04]
 [ 2.22220e+00  1.67100e+01  9.61200e+00  2.85440e+01]
 [ 1.56110e+00  5.17910e+00  1.68520e+00  8.42540e+00]]

Resolución

m21 = 0.6666666269302368
m31 = 0.4683346748352051

[[ 3.3333001e+00  1.5920000e+04 -1.0333300e+01  1.5913000e+04]
 [ 0.0000000e+00 -1.0596623e+04  1.6500866e+01 -1.0580122e+04]
 [ 0.0000000e+00 -7.4507090e+03  6.5246429e+00 -7.4441846e+03]]

 m32 = 0.7031210660934448

Matriz final:
[[ 3.3333001e+00  1.5920000e+04 -1.0333300e+01  1.5913000e+04]
 [ 0.0000000e+00 -1.0596623e+04  1.6500866e+01 -1.0580122e+04]
 [ 0.0000000e+00  0.0000000e+00 -5.0774632e+00 -5.0776367e+00]]

Sustitución hacia atrás

x3 = 1.000034213066101
x2 = 1.0
x1 = 1.0001059770584106

Solución final
x1 = 1.0001059770584106
x2 = 1.0
x3 = 1.000034213066101


c)

$x_1 + 1/2x_2 + 1/3x_3 + 1/4x_4= 1/6,$

$1/2x_1 + 1/3x_2 + 1/4x_3 + 1/5x_4 = 1/7,$

$1/3x_1 + 1/4x_2 + 1/5x_3 + 1/6x_4 = 1/8,$

$1/4x_1 + 1/5x_2 + 1/6x_3 + 1/7x_4 = 1/9.$

In [ ]:
import numpy as np

A = np.array([
    [1,     1/2,   1/3,   1/4,   1/6],
    [1/2,   1/3,   1/4,   1/5,   1/7],
    [1/3,   1/4,   1/5,   1/6,   1/8],
    [1/4,   1/5,   1/6,   1/7,   1/9]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución\n")

m21 = A[1,0] / A[0,0]
m31 = A[2,0] / A[0,0]
m41 = A[3,0] / A[0,0]

print(f"m21 = {m21}")
print(f"m31 = {m31}")
print(f"m41 = {m41}\n")

A[1] = A[1] - m21*A[0]
A[2] = A[2] - m31*A[0]
A[3] = A[3] - m41*A[0]

print(A)

m32 = A[2,1] / A[1,1]
m42 = A[3,1] / A[1,1]

print(f"\nm32 = {m32}")
print(f"m42 = {m42}\n")

A[2] = A[2] - m32*A[1]
A[3] = A[3] - m42*A[1]

print(A)

m43 = A[3,2] / A[2,2]
print(f"\nm43 = {m43}\n")

A[3] = A[3] - m43*A[2]

print("Matriz final:")
print(A)

print("\nSustitución hacia atrás\n")

x4 = A[3,4] / A[3,3]
print(f"x4 = {x4}")

x3 = (A[2,4] - A[2,3]*x4) / A[2,2]
print(f"x3 = {x3}")

x2 = (A[1,4] - A[1,2]*x3 - A[1,3]*x4) / A[1,1]
print(f"x2 = {x2}")

x1 = (A[0,4] - A[0,1]*x2 - A[0,2]*x3 - A[0,3]*x4) / A[0,0]
print(f"x1 = {x1}")

print("\nSolución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")
print(f"x4 = {x4}")

Matriz inicial:
[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.5        0.33333334 0.25       0.2        0.14285715]
 [0.33333334 0.25       0.2        0.16666667 0.125     ]
 [0.25       0.2        0.16666667 0.14285715 0.11111111]]

Resolución

m21 = 0.5
m31 = 0.3333333432674408
m41 = 0.25

[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.         0.08333334 0.08333333 0.075      0.05952381]
 [0.         0.08333333 0.08888888 0.08333334 0.06944444]
 [0.         0.075      0.08333334 0.08035715 0.06944445]]

m32 = 0.9999998211860657
m42 = 0.8999999165534973

[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.         0.08333334 0.08333333 0.075      0.05952381]
 [0.         0.         0.00555557 0.00833335 0.00992064]
 [0.         0.         0.00833335 0.01285715 0.01587302]]

m43 = 1.499998688697815

Matriz final:
[[1.0000000e+00 5.0000000e-01 3.3333334e-01 2.5000000e-01 1.6666667e-01]
 [0.0000000e+00 8.3333343e-02 8.3333328e-02 7.5000003e-02 5.

d)

$2x_1 + x_2 - x_3 + x_4 - 3x_5= 7,$

$x_1 + 2x_3 - x_4 + x_5= 2,$

$-2x_2 - x_3 + x_4 - x_5= -5,$

$3x_1 + x_2 - 4x_3 + x_5= 6,$

$x_1 - x_2 - x_3 - x_4 + x_5= -3.$

In [29]:
import numpy as np

A = np.array([
    [2,  1, -1,  1, -3,  7],
    [1,  0,  2, -1,  1,  2],
    [0, -2, -1,  1, -1, -5],
    [3,  1, -4,  0,  5,  6],
    [1, -1, -1, -1,  1, -3]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución\n")

m21 = A[1,0] / A[0,0]
m31 = A[2,0] / A[0,0]
m41 = A[3,0] / A[0,0]
m51 = A[4,0] / A[0,0]

print(f"m21 = {m21}")
print(f"m31 = {m31}")
print(f"m41 = {m41}")
print(f"m51 = {m51}\n")

A[1] = A[1] - m21*A[0]
A[2] = A[2] - m31*A[0]
A[3] = A[3] - m41*A[0]
A[4] = A[4] - m51*A[0]

print(A)

m32 = A[2,1] / A[1,1]
m42 = A[3,1] / A[1,1]
m52 = A[4,1] / A[1,1]

print(f"\nm32 = {m32}")
print(f"m42 = {m42}")
print(f"m52 = {m52}\n")

A[2] = A[2] - m32*A[1]
A[3] = A[3] - m42*A[1]
A[4] = A[4] - m52*A[1]

print(A)

m43 = A[3,2] / A[2,2]
m53 = A[4,2] / A[2,2]

print(f"\nm43 = {m43}")
print(f"m53 = {m53}\n")

A[3] = A[3] - m43*A[2]
A[4] = A[4] - m53*A[2]

print(A)

m54 = A[4,3] / A[3,3]
print(f"\nm54 = {m54}\n")

A[4] = A[4] - m54*A[3]

print("Matriz final:")
print(A)

print("\nSustitución hacia atrás\n")

x5 = A[4,5] / A[4,4]
print(f"x5 = {x5}")

x4 = (A[3,5] - A[3,4]*x5) / A[3,3]
print(f"x4 = {x4}")

x3 = (A[2,5] - A[2,3]*x4 - A[2,4]*x5) / A[2,2]
print(f"x3 = {x3}")

x2 = (A[1,5] - A[1,2]*x3 - A[1,3]*x4 - A[1,4]*x5) / A[1,1]
print(f"x2 = {x2}")

x1 = (A[0,5] - A[0,1]*x2 - A[0,2]*x3 - A[0,3]*x4 - A[0,4]*x5) / A[0,0]
print(f"x1 = {x1}")

print("\nSolución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")
print(f"x4 = {x4}")
print(f"x5 = {x5}")

Matriz inicial:
[[ 2.  1. -1.  1. -3.  7.]
 [ 1.  0.  2. -1.  1.  2.]
 [ 0. -2. -1.  1. -1. -5.]
 [ 3.  1. -4.  0.  5.  6.]
 [ 1. -1. -1. -1.  1. -3.]]

Resolución

m21 = 0.5
m31 = 0.0
m41 = 1.5
m51 = 0.5

[[ 2.   1.  -1.   1.  -3.   7. ]
 [ 0.  -0.5  2.5 -1.5  2.5 -1.5]
 [ 0.  -2.  -1.   1.  -1.  -5. ]
 [ 0.  -0.5 -2.5 -1.5  9.5 -4.5]
 [ 0.  -1.5 -0.5 -1.5  2.5 -6.5]]

m32 = 4.0
m42 = 1.0
m52 = 3.0

[[  2.    1.   -1.    1.   -3.    7. ]
 [  0.   -0.5   2.5  -1.5   2.5  -1.5]
 [  0.    0.  -11.    7.  -11.    1. ]
 [  0.    0.   -5.    0.    7.   -3. ]
 [  0.    0.   -8.    3.   -5.   -2. ]]

m43 = 0.4545454680919647
m53 = 0.7272727489471436

[[  2.          1.         -1.          1.         -3.          7.       ]
 [  0.         -0.5         2.5        -1.5         2.5        -1.5      ]
 [  0.          0.        -11.          7.        -11.          1.       ]
 [  0.          0.          0.         -3.1818182  12.         -3.4545455]
 [  0.          0.          0.         -2.090909

5. Dado el sistema lineal:

$𝑥_1 − 𝑥_2 + 𝛼𝑥_3 = −2,$

$−𝑥_1 + 2𝑥_2 − 𝛼𝑥_3 = 3,$

$𝛼𝑥_1 + 𝑥_2 + 𝑥_3 = 2.$

a) Encuentre el valor(es) de $𝛼$ para los que el sistema no tiene soluciones.

In [31]:
import numpy as np

a = 1.0  

A = np.array([
    [1,  -1,  a, -2],
    [-1,  2, -a,  3],
    [a,   1,  1,  2]
], dtype=float)

print("Matriz inicial:")
print(A)

print("\nResolución\n")

m21 = A[1,0] / A[0,0]
m31 = A[2,0] / A[0,0]

print(f"m21 = {m21}")
print(f"m31 = {m31}\n")

A[1] = A[1] - m21*A[0]
A[2] = A[2] - m31*A[0]

print(A)

m32 = A[2,1] / A[1,1]
print(f"\nm32 = {m32}\n")

A[2] = A[2] - m32*A[1]

print("Matriz final:")
print(A)

print("\nAnálisis de la última fila")

pivote = A[2,2]
constante = A[2,3]

print(f"Pivote = {pivote}")
print(f"Término independiente = {constante}")

if abs(pivote) < 1e-8 and abs(constante) > 1e-8:
    print("\nEl sistema NO tiene solución")
elif abs(pivote) < 1e-8 and abs(constante) < 1e-8:
    print("\nEl sistema tiene infinitas soluciones")
else:
    print("\nEl sistema tiene solución única")

Matriz inicial:
[[ 1. -1.  1. -2.]
 [-1.  2. -1.  3.]
 [ 1.  1.  1.  2.]]

Resolución

m21 = -1.0
m31 = 1.0

[[ 1. -1.  1. -2.]
 [ 0.  1.  0.  1.]
 [ 0.  2.  0.  4.]]

m32 = 2.0

Matriz final:
[[ 1. -1.  1. -2.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  0.  2.]]

Análisis de la última fila
Pivote = 0.0
Término independiente = 2.0

El sistema NO tiene solución


b) Encuentre el valor(es) de 𝛼 para los que el sistema tiene un número infinito de soluciones.

In [ ]:
import numpy as np

def revisar(a):
    
    A = np.array([
        [1, -1, a],
        [-1, 2, -a],
        [a, 1, 1]
    ], dtype=float)

    b = np.array([-2, 3, 2], dtype=float)

    Ab = np.column_stack((A, b))

    print(f"\nProbando con a = {a}")
    print("\nMatriz A =")
    print(A)
    print("\nMatriz Ab =")
    print(Ab)

    rango_A = np.linalg.matrix_rank(A)
    rango_Ab = np.linalg.matrix_rank(Ab)

    print("\nRango de A =", rango_A)
    print("Rango de Ab =", rango_Ab)

    if rango_A < 3 and rango_A == rango_Ab:
        print("\nEl sistema tiene infinitas soluciones.")
    else:
        print("\nEl sistema NO tiene infinitas soluciones.")

revisar(1)
revisar(-1)


Probando con a = 1

Matriz A =
[[ 1. -1.  1.]
 [-1.  2. -1.]
 [ 1.  1.  1.]]

Matriz Ab =
[[ 1. -1.  1. -2.]
 [-1.  2. -1.  3.]
 [ 1.  1.  1.  2.]]

Rango de A = 2
Rango de Ab = 3

El sistema NO tiene infinitas soluciones.

Probando con a = -1

Matriz A =
[[ 1. -1. -1.]
 [-1.  2.  1.]
 [-1.  1.  1.]]

Matriz Ab =
[[ 1. -1. -1. -2.]
 [-1.  2.  1.  3.]
 [-1.  1.  1.  2.]]

Rango de A = 2
Rango de Ab = 2

El sistema tiene infinitas soluciones.


c) Suponga que existe una única solución para una a determinada, encuentre la solución.

In [49]:
import numpy as np

A = np.array([
    [1, -1,  1, -2],
    [-1, 2, -1,  3],
    [1,  1,  1,  2]
], dtype=float)

print("Sistema con a = 1")
print("\nMatriz inicial:")
print(A)

print("\nResolución\n")

m21 = A[1,0] / A[0,0]
m31 = A[2,0] / A[0,0]

print(f"m21 = {m21}")
print(f"m31 = {m31}\n")

A[1] = A[1] - m21*A[0]
A[2] = A[2] - m31*A[0]

print(A)

m32 = A[2,1] / A[1,1]
print(f"\nm32 = {m32}\n")

A[2] = A[2] - m32*A[1]

print("Matriz final:")
print(A)

print("\nLa última fila queda toda en 0, por lo tanto hay infinitas soluciones.")

print("\nDe la matriz final obtenemos:")

print("\nEcuación 2:  x2 - x3 = 1   →   x2 = 1 + x3")
print("Ecuación 1:  x1 - x2 + x3 = -2")

print("\nSea x3 = t")

print("\nx1 - (1 + t) + t = -2")
print("x1 - 1 = -2")
print("x1 = -1")

print("\nPor lo tanto la solución general es:\n")

print("x1 = -1")
print("x2 = 1 + t")
print("x3 = t")


Sistema con a = 1

Matriz inicial:
[[ 1. -1.  1. -2.]
 [-1.  2. -1.  3.]
 [ 1.  1.  1.  2.]]

Resolución

m21 = -1.0
m31 = 1.0

[[ 1. -1.  1. -2.]
 [ 0.  1.  0.  1.]
 [ 0.  2.  0.  4.]]

m32 = 2.0

Matriz final:
[[ 1. -1.  1. -2.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  0.  2.]]

La última fila queda toda en 0, por lo tanto hay infinitas soluciones.

De la matriz final obtenemos:

Ecuación 2:  x2 - x3 = 1   →   x2 = 1 + x3
Ecuación 1:  x1 - x2 + x3 = -2

Sea x3 = t

x1 - (1 + t) + t = -2
x1 - 1 = -2
x1 = -1

Por lo tanto la solución general es:

x1 = -1
x2 = 1 + t
x3 = t


6. Suponga que en un sistema biológico existen n especies de animales y m fuentes de alimento. Si $𝑥_𝑗$ representa la población de las j-ésimas especies, para cada 𝑗 = 1, ⋯ , 𝑛; $𝑏_𝑖$; representa el suministro diario disponible del i-ésimo alimento y $𝑎_{𝑖𝑗}$ representa la cantidad del i-ésimo alimento.

$𝑎_{11}𝑥_1 + 𝑎{12}𝑥_2 + ⋯ + 𝑎{1𝑛}𝑥_𝑛 = 𝑏_1,$

$𝑎{21}𝑥_1 + 𝑎{22}𝑥_2 + ⋯ + 𝑎{2𝑛}𝑥_𝑛 = 𝑏_2,$

$⋮ ⋮ ⋮ ⋮$

$𝑎{𝑚1}𝑥_1 + 𝑎{𝑚2}𝑥_2 + ⋯ + 𝑎{𝑚𝑛}𝑥_𝑛 = 𝑏_𝑚,$

representa un equilibrio donde existe un suministro diario de alimento para cumplir con precisión con el promedio
diario de consumo de cada especie.

a) Si
𝐴 = [$𝑎_{𝑖𝑗}$] = 

[1 2 0 3

1 0 2 2

0 0 1 1]

𝐱 = ($𝑥_𝑗$) = [1000, 500, 350, 400], y b = ($𝑏_𝑖$) = [3500, 2700, 900]. ¿Existe suficiente alimento para satisfacer el consumo promedio diario?

In [3]:
import numpy as np

A = np.array([
    [1, 2, 0, 3],
    [1, 0, 2, 2],
    [0, 0, 1, 1]
], dtype=float)

x = np.array([1000, 500, 350, 400], dtype=float)

b = np.array([3500, 2700, 900], dtype=float)

print("Cconsumo por especie:")
print(A)

print("\nPoblación de especies:")
print(x)

print("\nAlimento disponible:")
print(b)

print("\nResolución:\n")

c1 = A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2] + A[0,3]*x[3]
c2 = A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2] + A[1,3]*x[3]
c3 = A[2,0]*x[0] + A[2,1]*x[1] + A[2,2]*x[2] + A[2,3]*x[3]

print(f"Alimento 1:  1({x[0]}) + 2({x[1]}) + 0({x[2]}) + 3({x[3]}) = {c1}")
print(f"Alimento 2:  1({x[0]}) + 0({x[1]}) + 2({x[2]}) + 2({x[3]}) = {c2}")
print(f"Alimento 3:  0({x[0]}) + 0({x[1]}) + 1({x[2]}) + 1({x[3]}) = {c3}")

Ax = np.array([c1, c2, c3])

print("\nConsumo total:")
print(Ax)

print("\nComparación alimento disponible vs consumo:")

for i in range(3):
    print(f"Alimento {i+1}: disponible = {b[i]}  requerido = {Ax[i]}  sobra = {b[i] - Ax[i]}")

if np.all(b >= Ax):
    print("\nRespuesta: SÍ existe suficiente alimento para todas las especies")
else:
    print("\nRespuesta: NO hay suficiente alimento")

Cconsumo por especie:
[[1. 2. 0. 3.]
 [1. 0. 2. 2.]
 [0. 0. 1. 1.]]

Población de especies:
[1000.  500.  350.  400.]

Alimento disponible:
[3500. 2700.  900.]

Resolución:

Alimento 1:  1(1000.0) + 2(500.0) + 0(350.0) + 3(400.0) = 3200.0
Alimento 2:  1(1000.0) + 0(500.0) + 2(350.0) + 2(400.0) = 2500.0
Alimento 3:  0(1000.0) + 0(500.0) + 1(350.0) + 1(400.0) = 750.0

Consumo total:
[3200. 2500.  750.]

Comparación alimento disponible vs consumo:
Alimento 1: disponible = 3500.0  requerido = 3200.0  sobra = 300.0
Alimento 2: disponible = 2700.0  requerido = 2500.0  sobra = 200.0
Alimento 3: disponible = 900.0  requerido = 750.0  sobra = 150.0

Respuesta: SÍ existe suficiente alimento para todas las especies


b) ¿Cuál es el número máximo de animales de cada especie que se podría agregar de forma individual al sistema
con el suministro de alimento que cumpla con el consumo?

In [9]:
import numpy as np

A = np.array([
    [1, 2, 0, 3],
    [1, 0, 2, 2],
    [0, 0, 1, 1]
], dtype=float)

x = np.array([1000, 500, 350, 400], dtype=float)

b = np.array([3500, 2700, 900], dtype=float)

c1 = A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2] + A[0,3]*x[3]
c2 = A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2] + A[1,3]*x[3]
c3 = A[2,0]*x[0] + A[2,1]*x[1] + A[2,2]*x[2] + A[2,3]*x[3]

Ax = np.array([c1, c2, c3])

sobra = b - Ax

max_extra = []

for especie in range(4):
    consumo_especie = A[:, especie]
    posibles = []

    for alimento in range(3):
        if consumo_especie[alimento] > 0:
            posibles.append(sobra[alimento] / consumo_especie[alimento])

    max_extra.append(min(posibles))

print("Máximo número adicional de animales por especie:")
for i in range(4):
    print(f"Especie {i+1}: {int(max_extra[i])}")

Máximo número adicional de animales por especie:
Especie 1: 200
Especie 2: 150
Especie 3: 100
Especie 4: 100


c) Si la especie 1 se extingue, ¿qué cantidad de incremento individual de las especies restantes se podría soportar?

In [12]:
import numpy as np

A = np.array([
    [1, 2, 0, 3],
    [1, 0, 2, 2],
    [0, 0, 1, 1]
], dtype=float)

x = np.array([0, 500, 350, 400], dtype=float)

b = np.array([3500, 2700, 900], dtype=float)

c1 = A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2] + A[0,3]*x[3]
c2 = A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2] + A[1,3]*x[3]
c3 = A[2,0]*x[0] + A[2,1]*x[1] + A[2,2]*x[2] + A[2,3]*x[3]

Ax = np.array([c1, c2, c3])

sobra = b - Ax

max_extra = []

for especie in range(1,4):
    consumo_especie = A[:, especie]
    posibles = []

    for alimento in range(3):
        if consumo_especie[alimento] > 0:
            posibles.append(sobra[alimento] / consumo_especie[alimento])

    max_extra.append(min(posibles))

print("Máximo incremento si la especie 1 desaparece:")
for i in range(3):
    print(f"Especie {i+2}: {int(max_extra[i])}")

Máximo incremento si la especie 1 desaparece:
Especie 2: 650
Especie 3: 150
Especie 4: 150


d) Si la especie 2 se extingue, ¿qué cantidad de incremento individual de las especies restantes se podría soportar?

In [16]:
import numpy as np

A = np.array([
    [1, 2, 0, 3],
    [1, 0, 2, 2],
    [0, 0, 1, 1]
], dtype=float)

x = np.array([1000, 0, 350, 400], dtype=float)

b = np.array([3500, 2700, 900], dtype=float)

c1 = A[0,0]*x[0] + A[0,1]*x[1] + A[0,2]*x[2] + A[0,3]*x[3]
c2 = A[1,0]*x[0] + A[1,1]*x[1] + A[1,2]*x[2] + A[1,3]*x[3]
c3 = A[2,0]*x[0] + A[2,1]*x[1] + A[2,2]*x[2] + A[2,3]*x[3]

Ax = np.array([c1, c2, c3])

sobra = b - Ax

max_extra = []

for especie in [0,2,3]:
    consumo_especie = A[:, especie]
    posibles = []
    for alimento in range(3):
        if consumo_especie[alimento] > 0:
            posibles.append(sobra[alimento] / consumo_especie[alimento])
    max_extra.append(min(posibles))

print("Máximo incremento si la especie 2 desaparece:")
print(f"Especie 1: {int(max_extra[0])}")
print(f"Especie 3: {int(max_extra[1])}")
print(f"Especie 4: {int(max_extra[2])}")

Máximo incremento si la especie 2 desaparece:
Especie 1: 200
Especie 3: 100
Especie 4: 100


7. Repita el ejercicio 4 con el método Gauss-Jordan

a)

$1/4x_1 + 1/5x_2 + 1/6x_3 = 9,$

$1/3x_1 + 1/4x_2 + 1/5x_3 = 8,$

$1/2x_1 + x_2 + 2x_3 = 8.$

In [17]:
import numpy as np

A = np.array([
    [1/4, 1/5, 1/6, 9],
    [1/3, 1/4, 1/5, 8],
    [1/2, 1.0, 2.0, 8]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución por Gauss-Jordan\n")

pivote1 = np.float32(A[0,0])
A[0] = np.float32(A[0] / pivote1)

print(A, "\n")

m10 = np.float32(A[1,0])
m20 = np.float32(A[2,0])

A[1] = np.float32(A[1] - m10*A[0])
A[2] = np.float32(A[2] - m20*A[0])

print(A, "\n")

pivote2 = np.float32(A[1,1])
A[1] = np.float32(A[1] / pivote2)

print(A, "\n")

m01 = np.float32(A[0,1])
m21 = np.float32(A[2,1])

A[0] = np.float32(A[0] - m01*A[1])
A[2] = np.float32(A[2] - m21*A[1])

print(A, "\n")

pivote3 = np.float32(A[2,2])
A[2] = np.float32(A[2] / pivote3)

print(A, "\n")

m02 = np.float32(A[0,2])
m12 = np.float32(A[1,2])

A[0] = np.float32(A[0] - m02*A[2])
A[1] = np.float32(A[1] - m12*A[2])

print("Matriz final:")
print(A)

x1 = A[0,3]
x2 = A[1,3]
x3 = A[2,3]

print("\nSolución final:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")


Matriz inicial:
[[0.25       0.2        0.16666667 9.        ]
 [0.33333334 0.25       0.2        8.        ]
 [0.5        1.         2.         8.        ]]

Resolución por Gauss-Jordan

[[ 1.          0.8         0.6666667  36.        ]
 [ 0.33333334  0.25        0.2         8.        ]
 [ 0.5         1.          2.          8.        ]] 

[[ 1.0000000e+00  8.0000001e-01  6.6666669e-01  3.6000000e+01]
 [ 0.0000000e+00 -1.6666681e-02 -2.2222236e-02 -4.0000000e+00]
 [ 0.0000000e+00  6.0000002e-01  1.6666666e+00 -1.0000000e+01]] 

[[  1.          0.8         0.6666667  36.       ]
 [ -0.          1.          1.333333  239.9998   ]
 [  0.          0.6         1.6666666 -10.       ]] 

[[   1.           0.          -0.3999998 -155.99985  ]
 [  -0.           1.           1.333333   239.9998   ]
 [   0.           0.           0.8666668 -153.9999   ]] 

[[   1.           0.          -0.3999998 -155.99985  ]
 [  -0.           1.           1.333333   239.9998   ]
 [   0.           0.          

b)

$3.333x_1 + 15920x_2 - 10.333x_3 = 15913,$

$2.222x_1 + 16.71x_2 + 9.612x_3 = 28.544,$

$1.5611x_1 + 5.1791x_2 + 1.6852x_3 = 8.4254.$

In [24]:
import numpy as np

A = np.array([
    [3.3333, 15920,  -10.3333, 15913],
    [2.2222, 16.71,    9.612,   28.544],
    [1.5611, 5.1791,   1.6852,  8.4254]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución por Gauss-Jordan\n")

p1 = np.float32(A[0,0])
A[0] = np.float32(A[0] / p1)

print(A, "\n")

m10 = np.float32(A[1,0])
m20 = np.float32(A[2,0])

A[1] = np.float32(A[1] - m10*A[0])
A[2] = np.float32(A[2] - m20*A[0])

print(A, "\n")

p2 = np.float32(A[1,1])
A[1] = np.float32(A[1] / p2)

print(A, "\n")

m01 = np.float32(A[0,1])
m21 = np.float32(A[2,1])

A[0] = np.float32(A[0] - m01*A[1])
A[2] = np.float32(A[2] - m21*A[1])

print(A, "\n")

p3 = np.float32(A[2,2])
A[2] = np.float32(A[2] / p3)

print(A, "\n")

m02 = np.float32(A[0,2])
m12 = np.float32(A[1,2])

A[0] = np.float32(A[0] - m02*A[2])
A[1] = np.float32(A[1] - m12*A[2])

print("Matriz final:")
print(A)

x1 = A[0,3]
x2 = A[1,3]
x3 = A[2,3]

print("\nSolución final:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")


Matriz inicial:
[[ 3.33330e+00  1.59200e+04 -1.03333e+01  1.59130e+04]
 [ 2.22220e+00  1.67100e+01  9.61200e+00  2.85440e+01]
 [ 1.56110e+00  5.17910e+00  1.68520e+00  8.42540e+00]]

Resolución por Gauss-Jordan

[[ 1.0000000e+00  4.7760474e+03 -3.1000209e+00  4.7739478e+03]
 [ 2.2221999e+00  1.6709999e+01  9.6120005e+00  2.8544001e+01]
 [ 1.5611000e+00  5.1791000e+00  1.6852000e+00  8.4253998e+00]] 

[[ 1.0000000e+00  4.7760474e+03 -3.1000209e+00  4.7739478e+03]
 [ 0.0000000e+00 -1.0596622e+04  1.6500866e+01 -1.0580122e+04]
 [ 0.0000000e+00 -7.4507085e+03  6.5246429e+00 -7.4441846e+03]] 

[[ 1.0000000e+00  4.7760474e+03 -3.1000209e+00  4.7739478e+03]
 [-0.0000000e+00  1.0000000e+00 -1.5571817e-03  9.9844289e-01]
 [ 0.0000000e+00 -7.4507085e+03  6.5246429e+00 -7.4441846e+03]] 

[[ 1.0000000e+00  0.0000000e+00  4.3371525e+00  5.3374023e+00]
 [-0.0000000e+00  1.0000000e+00 -1.5571817e-03  9.9844289e-01]
 [ 0.0000000e+00  0.0000000e+00 -5.0774641e+00 -5.0776367e+00]] 

[[ 1.0000000e+00  0.

c)

$x_1 + 1/2x_2 + 1/3x_3 + 1/4x_4= 1/6,$

$1/2x_1 + 1/3x_2 + 1/4x_3 + 1/5x_4 = 1/7,$

$1/3x_1 + 1/4x_2 + 1/5x_3 + 1/6x_4 = 1/8,$

$1/4x_1 + 1/5x_2 + 1/6x_3 + 1/7x_4 = 1/9.$

In [23]:
import numpy as np

A = np.array([
    [1,     1/2,   1/3,   1/4,   1/6],
    [1/2,   1/3,   1/4,   1/5,   1/7],
    [1/3,   1/4,   1/5,   1/6,   1/8],
    [1/4,   1/5,   1/6,   1/7,   1/9]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución por Gauss-Jorda\n")

p1 = np.float32(A[0,0])
A[0] = np.float32(A[0] / p1)

m10 = np.float32(A[1,0])
m20 = np.float32(A[2,0])
m30 = np.float32(A[3,0])

A[1] = np.float32(A[1] - m10*A[0])
A[2] = np.float32(A[2] - m20*A[0])
A[3] = np.float32(A[3] - m30*A[0])

print(A, "\n")

p2 = np.float32(A[1,1])
A[1] = np.float32(A[1] / p2)

m01 = np.float32(A[0,1])
m21 = np.float32(A[2,1])
m31 = np.float32(A[3,1])

A[0] = np.float32(A[0] - m01*A[1])
A[2] = np.float32(A[2] - m21*A[1])
A[3] = np.float32(A[3] - m31*A[1])

print(A, "\n")

p3 = np.float32(A[2,2])
A[2] = np.float32(A[2] / p3)

m02 = np.float32(A[0,2])
m12 = np.float32(A[1,2])
m32 = np.float32(A[3,2])

A[0] = np.float32(A[0] - m02*A[2])
A[1] = np.float32(A[1] - m12*A[2])
A[3] = np.float32(A[3] - m32*A[2])

print(A, "\n")

p4 = np.float32(A[3,3])
A[3] = np.float32(A[3] / p4)

m03 = np.float32(A[0,3])
m13 = np.float32(A[1,3])
m23 = np.float32(A[2,3])

A[0] = np.float32(A[0] - m03*A[3])
A[1] = np.float32(A[1] - m13*A[3])
A[2] = np.float32(A[2] - m23*A[3])

print("Matriz final:")
print(A)

x1 = A[0,4]
x2 = A[1,4]
x3 = A[2,4]
x4 = A[3,4]

print("\nSolución final:")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")
print(f"x4 = {x4}")


Matriz inicial:
[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.5        0.33333334 0.25       0.2        0.14285715]
 [0.33333334 0.25       0.2        0.16666667 0.125     ]
 [0.25       0.2        0.16666667 0.14285715 0.11111111]]

Resolución por Gauss-Jorda

[[1.         0.5        0.33333334 0.25       0.16666667]
 [0.         0.08333334 0.08333333 0.075      0.05952381]
 [0.         0.08333333 0.08888888 0.08333334 0.06944444]
 [0.         0.075      0.08333334 0.08035715 0.06944445]] 

[[ 1.          0.         -0.16666657 -0.19999996 -0.19047616]
 [ 0.          1.          0.9999998   0.8999999   0.7142857 ]
 [ 0.          0.          0.00555557  0.00833335  0.00992064]
 [ 0.          0.          0.00833335  0.01285715  0.01587302]] 

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  4.9999669e-02
   1.0714202e-01]
 [ 0.0000000e+00  1.0000000e+00  0.0000000e+00 -5.9999853e-01
  -1.0714242e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00  1.4999987e+00
   1.78571

d)

$2x_1 + x_2 - x_3 + x_4 - 3x_5= 7,$

$x_1 + 2x_3 - x_4 + x_5= 2,$

$-2x_2 - x_3 + x_4 - x_5= -5,$

$3x_1 + x_2 - 4x_3 + x_5= 6,$

$x_1 - x_2 - x_3 - x_4 + x_5= -3.$

In [20]:
import numpy as np

A = np.array([
    [2,  1, -1,  1, -3,  7],
    [1,  0,  2, -1,  1,  2],
    [0, -2, -1,  1, -1, -5],
    [3,  1, -4,  0,  5,  6],
    [1, -1, -1, -1,  1, -3]
], dtype=np.float32)

print("Matriz inicial:")
print(A)

print("\nResolución por Gauss-Jordan\n")

p1 = np.float32(A[0,0])
A[0] = np.float32(A[0] / p1)

m10=A[1,0]; m20=A[2,0]; m30=A[3,0]; m40=A[4,0]

A[1]=np.float32(A[1]-m10*A[0])
A[2]=np.float32(A[2]-m20*A[0])
A[3]=np.float32(A[3]-m30*A[0])
A[4]=np.float32(A[4]-m40*A[0])

print(A,"\n")

p2 = np.float32(A[1,1])
A[1] = np.float32(A[1] / p2)

m01=A[0,1]; m21=A[2,1]; m31=A[3,1]; m41=A[4,1]

A[0]=np.float32(A[0]-m01*A[1])
A[2]=np.float32(A[2]-m21*A[1])
A[3]=np.float32(A[3]-m31*A[1])
A[4]=np.float32(A[4]-m41*A[1])

print(A,"\n")

p3 = np.float32(A[2,2])
A[2] = np.float32(A[2] / p3)

m02=A[0,2]; m12=A[1,2]; m32=A[3,2]; m42=A[4,2]

A[0]=np.float32(A[0]-m02*A[2])
A[1]=np.float32(A[1]-m12*A[2])
A[3]=np.float32(A[3]-m32*A[2])
A[4]=np.float32(A[4]-m42*A[2])

print(A,"\n")

p4 = np.float32(A[3,3])
A[3] = np.float32(A[3] / p4)

m03=A[0,3]; m13=A[1,3]; m23=A[2,3]; m43=A[4,3]

A[0]=np.float32(A[0]-m03*A[3])
A[1]=np.float32(A[1]-m13*A[3])
A[2]=np.float32(A[2]-m23*A[3])
A[4]=np.float32(A[4]-m43*A[3])

print(A,"\n")

p5 = np.float32(A[4,4])
A[4] = np.float32(A[4] / p5)

m04=A[0,4]; m14=A[1,4]; m24=A[2,4]; m34=A[3,4]

A[0]=np.float32(A[0]-m04*A[4])
A[1]=np.float32(A[1]-m14*A[4])
A[2]=np.float32(A[2]-m24*A[4])
A[3]=np.float32(A[3]-m34*A[4])

print("Matriz final:")
print(A)

x1=A[0,5]
x2=A[1,5]
x3=A[2,5]
x4=A[3,5]
x5=A[4,5]

print("\nSolución final")
print(f"x1 = {x1}")
print(f"x2 = {x2}")
print(f"x3 = {x3}")
print(f"x4 = {x4}")
print(f"x5 = {x5}")


Matriz inicial:
[[ 2.  1. -1.  1. -3.  7.]
 [ 1.  0.  2. -1.  1.  2.]
 [ 0. -2. -1.  1. -1. -5.]
 [ 3.  1. -4.  0.  5.  6.]
 [ 1. -1. -1. -1.  1. -3.]]

Resolución por Gauss-Jordan

[[ 1.   0.5 -0.5  0.5 -1.5  3.5]
 [ 0.  -0.5  2.5 -1.5  2.5 -1.5]
 [ 0.  -2.  -1.   1.  -1.  -5. ]
 [ 0.  -0.5 -2.5 -1.5  9.5 -4.5]
 [ 0.  -1.5 -0.5 -1.5  2.5 -6.5]] 

[[  1.   0.   2.  -1.   1.   2.]
 [ -0.   1.  -5.   3.  -5.   3.]
 [  0.   0. -11.   7. -11.   1.]
 [  0.   0.  -5.   0.   7.  -3.]
 [  0.   0.  -8.   3.  -5.  -2.]] 

[[ 1.          0.          0.          0.27272725 -1.          2.1818182 ]
 [-0.          1.          0.         -0.18181801  0.          2.5454545 ]
 [-0.         -0.          1.         -0.6363636   1.         -0.09090909]
 [ 0.          0.          0.         -3.181818   12.         -3.4545455 ]
 [ 0.          0.          0.         -2.090909    3.         -2.7272727 ]] 

[[ 1.          0.          0.          0.          0.02857137  1.8857143 ]
 [-0.          1.          0.